### ISSUE TITLE
Dedicated Server Fails to Load on Startup

### ISSUE THREAD

**Issue by JoelZBub** [spoorn/SpoornPink#1]
Versions:
Fabric 1.18.1-0.13.1
Fabric API 0.46.4+1.18
Cloth Config API 6,2,57 Fabric
SpoornPacks 1.1
SpoornPink 1.0
TerraBlender Fabric 1.18.1-1.1.0.73

Dedicated server crashes/hangs on startup with errors from SpoornPink
No Crashlog generated.
latest.log here:
https://gist.github.com/JoelZBub/451e1ceba29d912373de23266a1236e7

**Comment by spoorn** [comment]
Thanks for catching this!

Fixed in the latest release of SpoornPacks: https://github.com/spoorn/SpoornPacks/commit/3303ccf6bf37eee19c55b11ac621f04b34e65fa1

Try updating SpoornPacks to 1.2 as that may be all you need to fix the problem.  Please reopen if the issue persists
