### ISSUE TITLE
Already registered in SpoornPacks error

### ISSUE THREAD

**Issue by darkqueen1229** [spoorn/SpoornPink#3]
I get the following error when I try to access my resources packs from the in-game pause menu with Pink installed.

Description: mouseClicked event handler
java.lang.RuntimeException:` Namespace [spoornpink] was already registered in SpoornPacks!

I do have the full crash report if needed.

**Comment by spoorn** [comment]
Could you attach the crash report?

**Comment by spoorn** [comment]
Never mind, I was able to reproduce it myself, will be fixed in the next release

**Comment by spoorn** [comment]
Please update to the latest SpoornPacks: https://www.curseforge.com/minecraft/mc-mods/spoornpacks/files/3645325

Let me know if the issue persists
