### ISSUE TITLE
Causes BYG and Terralith biomes to almost never generate

### ISSUE THREAD

**Issue by morgybc** [spoorn/SpoornPink#5]
Almost all BYG and Terralith biomes are replaced with vanilla biomes, usually with the closest ones being thousands of blocks from spawn. The issue is fully fixed when Pink is removed.
Modlist:
	- additionaladditions 4.0.0
	- antighost 1.18.2-fabric0.47.10-1.1.4
	- appleskin 2.4.0+mc1.18.2
	- architectury 4.3.53
	- attackspeedench 1.0
	- badpackets 0.1.2
	- balm-fabric 3.0.0+0
	- bclib 1.4.5
	- betteranimalsplus 1.18.2-11.0.5
	- betterbiomeblend 1.18.2-1.3.4-fabric
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterend 1.1.0
	- bettermineshafts 1.18.2-Fabric-2.1.0
	- betternether 6.1.1
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- blossom 1.18.2-1.0.4
	- blue_endless_jankson 1.2.1 via jankson
	- bookshelf 13.0.13
	- byg 1.4
	- cardinal-components-base 4.1.3 via trinkets
	- cardinal-components-entity 4.1.3 via trinkets
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.2.57
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-scissors-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- clumps 8.0.0+8
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_fasterxml_jackson_core_jackson-annotations 2.13.1 via spoornpacks
	- com_fasterxml_jackson_core_jackson-core 2.13.1 via spoornpacks
	- com_fasterxml_jackson_core_jackson-databind 2.13.1 via spoornpacks
	- continuity 1.1.0+1.18.2
	- controlling 9.0+19
	- crawl 0.10.6
	- cropxp 1.18.2-1.0.1
	- crowdin-translate 1.4+1.18.2 via antighost
	- dawn 3.3.0
	- decorative_blocks 2.1.0
	- disable_custom_worlds_advice 2.0
	- enchdesc 10.0.3
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.4
	- farmersdelight 1.18.2-0.2.1
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- go-fish 1.5.0-1.18.2
	- indium 1.0.3+mc1.18.2
	- inmis 2.5.3-1.18.2
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- journeymap-api-fabric 1.18.2-1.8-fabric-SNAPSHOT via journeymap-fabric
	- journeymap-fabric 5.8.3
	- kubejs 1802.5.1-build.363
	- lazydfu 0.1.2
	- libgui 5.1.0+1.18 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.9
	- macawsbridgesbyg 1.18.2-1.0
	- macawsroofsbyg 1.18.2-1.0
	- magicalforest 2.0.2
	- mcdar 1.4.8
	- mcwbridges 2.0.2
	- mcwdoors 1.0.6
	- mcwfences 1.0.4
	- mcwlights 1.0.3
	- mcwpaintings 1.0.3
	- mcwroofs 2.1.2
	- mcwtrpdoors 1.0.5
	- mcwwindows 2.0.3
	- me_hypherionmc_simple-rpc-common 3.0.0 via simple-rpc
	- minecraft 1.18.2
	- mm 2.3 via crawl
	- modmenu 3.2.1
	- more-axolotls 1.0.2
	- mousetweaks 2.22
	- naturescompass 1.18.2-2.0.3-fabric
	- nears 1.1.8
	- notenoughcrashes 4.1.6+1.18.2
	- observable 2.2.3
	- omega-config 1.2.3-1.18.1 via inmis
	- org_jetbrains_kotlin_kotlin-reflect 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- oxidized 1.6.4
	- patchouli 1.18.2-67-FABRIC
	- quartzelv 2.1.1+1.18
	- rhino 1801.1.9-build.135
	- roughlyenoughitems 8.1.457
	- roughlyenoughresources 2.5.0
	- seedfix 1.0.1
	- simple-rpc 3.0.0
	- sodium 0.4.1+build.15
	- spark 1.9.1
	- spoornpacks 4.2.1-1.18.2
	- spoornpink 3.3
	- starlight 1.0.2+fabric.89b8d9f
	- terrablender 1.1.0.99
	- terrarianslimes 1.2-BETA+1.18
	- trinketofundying 2.0.1-1.18
	- trinkets 3.3.0
	- voicechat 1.18.2-2.2.32
	- waystones 2.5.0
	- wthit 4.10.1
	- yigd 1.3.1
	- yungsapi 1.18.2-Fabric-2.0.8
	- yungsbridges 1.18.2-Fabric-2.1.0
	- yungsextras 1.18.2-Fabric-2.1.0
	- zihlaunchpads 1.2.0

**Comment by spoorn** [comment]
You don't have Terralith in your modlist

**Comment by morgybc** [comment]
On further inspection there is a lack of evidence for this issue.
